### ISSUE TITLE
Access using ingress

### ISSUE THREAD

**Issue by j-rewerts** [hoeghh/k8s-minecraft#3]
I noticed you were planning on adding an ingress resource for accessing the deployment. Have you had any luck?

**Comment by dvdblk** [comment]
Hey, I would like to do this as well. Have you tried it? @j-rewerts @hoeghh

**Comment by hoeghh** [comment]
I havent played with this for a long time. The new ingress controllers should support TCP but i havent tried it yet on this project. My plan back then was to add some statistics or dashboard with data from the game. But i never found the time, sorry,.
